version: "3"
services:
  node:
    # https://aka.ms/vscode-remote/containers/non-root
    user: node

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ..:/home/node/workspace:cached
      - node_modules:/home/node/workspace/node_modules
      - vscode_server:/home/node/.vscode-server/extensions
      - vscode_server_insiders:/home/node/.vscode-server-insiders/extensions
      # Use your ssh keys from within the container... entrypoint.sh will fix the permissions
      - ~/.ssh:/tmp/.ssh:cached,ro
      # In case you load bash with default settings, changing the history file location
      # prevents the history from being truncated. Add this to your .bashrc:
      # HISTFILE=~/.my_bash_history
      # If you end up with a folder on the host, delete it and create a new file, and rebuild the container
      - ~/.my_bash_history:/home/node/.my_bash_history:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    networks:
      - default

volumes:
  node_modules:
  vscode_server:
  vscode_server_insiders:
